apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd-demo
  namespace: default
  labels:
    app: python-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-cicd-demo
  template:
    metadata:
      labels:
        app: python-cicd-demo
    spec:
      containers:
      - name: python-app
        image: asmabadrwork/python-cicd-demo:629ef0bb4b8976ac1852aa89534b02f23e2e43f7
        ports:
        - containerPort: 5000
