name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - uat

jobs:
  python-ci:
    uses: vishuops0210/shared-repo/.github/workflows/ci-python.yml@main
    with:
      python-version: '3.12'
      enable-gitleaks: true
      gitleaks-fetch-depth: '10'
      enable-unit-tests: true
      install-command: |
        if [ ! -d ".venv" ]; then python -m venv .venv; fi
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      test-command: |
        source .venv/bin/activate
        PYTHONPATH=. pytest tests/ --cov=. --cov-report=xml:coverage.xml --cov-report=term-missing --junitxml=test-results.xml

      enable-sonarqube: true
      sonar-project-key: 'python-cicd-demo'
      sonar-exclusions: 'venv/**,__pycache__/**,.github/**'
      sonar-args: >
        -Dsonar.sources=app.py
        -Dsonar.tests=tests
        -Dsonar.test.inclusions=tests/**
        -Dsonar.python.coverage.reportPaths=coverage.xml
        -Dsonar.python.xunit.reportPath=test-results.xml

      enable-trivy-fs: true
      enable-trivy-image: true

      enable-docker-build: true
      enable-docker-push: true
      enable-image-size-check: true

      enable-ecr-push: true
      aws-region: 'ap-south-1'

      docker-repository: 'python-cicd-demo'
      docker-tag: ${{ github.sha }}
      max-image-size-mb: '500'

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  # --- CONTINUOUS DELIVERY (CD) TRIGGER ---
  update-cd-manifest:
    name: Update K8s Manifest for CD
    needs: python-ci
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Image Tag in k8s/deployment.yaml
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/python-cicd-demo:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit and Push K8s Manifest
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(cd): update image tag to ${{ github.sha }}"
          git push
